### PR TITLE
Fixes ReconcileVA for non-migratable drivers

### LINKED ISSUE #243: Is reconciling only available for in-Tree drivers?
Hello, After enabling `csi.ControllerServiceCapability_RPC_LIST_VOLUMES_PUBLISHED_NODES` in controllerserver and including the PublishedNodeIDs field in the ListVolumes response. We started to see the following log message from the csi-attacher sidecar. And I found the following function called as part of the reconciling code from the sidecar:

```
// RepairVolumeHandle generates a correct volume handle based on node ID information.
func (CSITranslator) RepairVolumeHandle(driverName, volumeHandle, nodeID string) (string, error) {
	if plugin, ok := inTreePlugins[driverName]; ok {
		return plugin.RepairVolumeHandle(volumeHandle, nodeID)
	}
	return "", fmt.Errorf("could not find In-Tree driver name for CSI plugin %v", driverName)
}
```
is reconciling not supported for non in-tree CSI drivers? thanks in Advance for your help

### PR DESCRIPTION
**Pull request by yuga711**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR fixes an issue in the volume attachment reconciler. Currently, the reconciler calls a method (unconditionally) that is supposed to be called only when the corresponding volume driver implements the in-tree plugin. 
The PR also fixes a few existing broken tests.

**Which issue(s) this PR fixes**:

Fixes #243

**Special notes for your reviewer**:

Tested the fix with csi-mock driver. The driver does not implement in-tree plugin.
Without the fix, the reconciler failed as below:

```
W0806 02:35:26.595059       1 csi_handler.go:159] Failed to repair volume handle  for driver io.kubernetes.storage.mock: could not find In-Tree driver name for CSI plugin io.kubernetes.storage.mock
```

With the fix, no such failure was observed.

**Does this PR introduce a user-facing change?**:

```release-note
Fixes an issue that results in a failure in volume attachment reconciler when the corresponding driver does not implement in-tree plugin. 
```

### CODE REVIEW

File: pkg/controller/csi_handler.go [hunk 1]
```diff
@@ -354,6 +357,22 @@ func (h *csiHandler) hasVAFinalizer(va *storage.VolumeAttachment) bool {
...
+// in-tree to CSI.
+func (h *csiHandler) isMigratable(va *storage.VolumeAttachment) bool {
+	if va.Spec.Source.PersistentVolumeName != nil {
+		pv, err := h.pvLister.Get(*va.Spec.Source.PersistentVolumeName)
+		if err != nil {
+			return false
+		}
+		return h.translator.IsPVMigratable(pv)
+	} else if va.Spec.Source.InlineVolumeSpec != nil {
+		return va.Spec.Source.InlineVolumeSpec.CSI != nil
```
Comment (yuga711) [inline pkg/controller/csi_handler.go:370]: @msau42: I am not sure if this is the right check for inline vols. Please suggest.

Comment (jsafrane) [reply pkg/controller/csi_handler.go:370]: It looks like the right check.

File: vendor/modules.txt [hunk 2]
```diff
@@ -3,10 +3,13 @@ github.com/beorn7/perks/quantile
 # github.com/blang/semver v3.5.0+incompatible
 github.com/blang/semver
 # github.com/container-storage-interface/spec v1.2.0
+## explicit
```
Comment (jsafrane) [inline vendor/modules.txt:6]: You must use golang 1.13 to generate vendor. And why is there any vendor change at all? There is no new import in the code.

**Comment by jsafrane** [comment]
Can you please check the unit tests? They test with "com.test.foo" driver. Why did they succeed? Should they be fixed? Or can you  please add a new unit test that covers your code change?

File: pkg/controller/csi_handler.go [hunk 3]
```diff
@@ -354,6 +357,22 @@ func (h *csiHandler) hasVAFinalizer(va *storage.VolumeAttachment) bool {
 	return false
 }
 
+// Checks if the PV (or) the inline-volume corresponding to the VA could have migrated from
+// in-tree to CSI.
+func (h *csiHandler) isMigratable(va *storage.VolumeAttachment) bool {
+	if va.Spec.Source.PersistentVolumeName != nil {
+		pv, err := h.pvLister.Get(*va.Spec.Source.PersistentVolumeName)
+		if err != nil {
+			return false
```
Comment (msau42) [inline pkg/controller/csi_handler.go:366]: should we return error instead of false?

**Comment by msau42** [comment]
Can you update the PR title and description to be more specific to the issue, something like "Fixes ReconcileVA for non-migratable drivers"

File: vendor/modules.txt (hunk 2 above)
Comment (yuga711) [reply vendor/modules.txt:6]: Yes, fixed it.

File: pkg/controller/csi_handler.go (hunk 3 above)
Comment (yuga711) [reply pkg/controller/csi_handler.go:366]: Yes, makesense.

**Comment by yuga711** [comment]
> > Can you please check the unit tests? They test with "com.test.foo" driver. Why did they succeed? Should they be fixed? Or can you please add a new unit test that covers your code change?
> 
> I was curious about this too. We seem to already have unit tests for [ReconcileVA](https://github.com/kubernetes-csi/external-attacher/blob/298cb965f909f76f2d2dfa2062cb5e142f14b9d5/pkg/controller/csi_handler_test.go). I think it's because the fake for RepairVolumeHandle [always succeeds](https://github.com/kubernetes-csi/external-attacher/blob/298cb965f909f76f2d2dfa2062cb5e142f14b9d5/pkg/controller/framework_test.go#L528). I wonder though, why do we need a fake translator? Can we use the real one?

Switched to real translator. Added new checks. Fixed several broken existing tests.

File: pkg/controller/csi_handler.go [hunk 4]
```diff
@@ -153,11 +153,19 @@ func (h *csiHandler) ReconcileVA() error {
 		}
 		attachedStatus := va.Status.Attached
 
-		volumeHandle, err = h.translator.RepairVolumeHandle(source.Driver, volumeHandle, nodeID)
+		// If volume driver has corresponding in-tree plugin, generate a correct volumehandle
+		isMig, err := h.isMigratable(va)
 		if err != nil {
-			klog.Warningf("Failed to repair volume handle %s for driver %s: %v", volumeHandle, source.Driver, err)
+			klog.Warningf("Failed to check if migratable: %v", err)
```
Comment (msau42) [inline pkg/controller/csi_handler.go:159]: Can you log the volume handle too?

File: pkg/controller/csi_handler.go [hunk 5]
```diff
@@ -354,6 +362,22 @@ func (h *csiHandler) hasVAFinalizer(va *storage.VolumeAttachment) bool {
...
+// in-tree to CSI.
+func (h *csiHandler) isMigratable(va *storage.VolumeAttachment) (bool, error) {
+	if va.Spec.Source.PersistentVolumeName != nil {
+		pv, err := h.pvLister.Get(*va.Spec.Source.PersistentVolumeName)
+		if err != nil {
+			return false, err
+		}
+		return h.translator.IsPVMigratable(pv), nil
+	} else if va.Spec.Source.InlineVolumeSpec != nil {
+		return va.Spec.Source.InlineVolumeSpec.CSI != nil, nil
```
Comment (msau42) [inline pkg/controller/csi_handler.go:375]: I think it should be an error if InlineVolumeSpec is set, but CSI is nil

File: pkg/controller/framework_test.go [hunk 6]
```diff
@@ -297,6 +302,13 @@ func runTests(t *testing.T, handlerFactory handlerFactory, tests []testCase) {
 		if test.additionalCheck != nil {
 			test.additionalCheck(t, test)
 		}
+		// makesure all the csi calls were executed.
+		if csiConnection.index < len(csiConnection.calls) {
```
Comment (msau42) [inline pkg/controller/framework_test.go:306]: Is it guaranteed that the test will run the reconciler loop exactly the same number of times?

File: pkg/controller/csi_handler_test.go [hunk 7]
```diff
@@ -34,6 +34,7 @@ import (
 	"k8s.io/client-go/informers"
 	"k8s.io/client-go/kubernetes"
 	core "k8s.io/client-go/testing"
+	csitranslator "k8s.io/csi-translation-lib"
```
Comment (msau42) [inline pkg/controller/csi_handler_test.go:37]: Can we add a test case for ReconcileVA using a volume type that does support migration?

**Comment by msau42** [comment]
Did you try running the fixed tests without your fix to ReconcileVA, to see if the test fails as expected?

File: pkg/controller/csi_handler.go (hunk 5 above)
Comment (yuga711) [reply pkg/controller/csi_handler.go:375]: ack

File: pkg/controller/framework_test.go (hunk 6 above)
Comment (yuga711) [reply pkg/controller/framework_test.go:306]: I think yes. Otherwise, I think we need to fix such tests.

File: pkg/controller/csi_handler_test.go (hunk 7 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go:37]: [These](https://github.com/kubernetes/kubernetes/blob/ded1f58779d0d2570735a6ebe7428d57a100ca97/staging/src/k8s.io/csi-translation-lib/translate.go#L29) are the ones that truly support in the actual translator. Do you suggest unit tests based on this? (or) we could setup a fake translator that migration support. If it's more work, can we do this separately?

**Comment by yuga711** [comment]
> Did you try running the fixed tests without your fix to ReconcileVA, to see if the test fails as expected?

Yes, the tests fail as expected when I ran them without fix. ie the tests complain saying the expected number of csi calls were not run...

File: pkg/controller/csi_handler.go (hunk 4 above)
Comment (yuga711) [reply pkg/controller/csi_handler.go:159]: ack

File: pkg/controller/csi_handler_test.go [hunk 8]
```diff
@@ -696,7 +697,7 @@ func TestCSIHandler(t *testing.T) {
 		{
 			name:           "unknown node -> error",
 			initialObjects: []runtime.Object{pvWithFinalizer()},
-			addedVA:        va(false, fin, ann),
+			addedVA:        va(false, fin, nil),
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:700]: Is this change necessary? My tests shows that presence of the annotation does not make any difference, because status is patched, not the object with its finalizers. Having `ann` in the `addedVA` is more correct, as the Patch below expects it's present in the original object.

File: pkg/controller/csi_handler_test.go [hunk 9]
```diff
@@ -833,8 +834,17 @@ func TestCSIHandler(t *testing.T) {
...
 					types.MergePatchType, patch(va(false /*attached*/, "" /*finalizer*/, nil /* annotations */),
 						va(false /*attached*/, fin, ann))),
-				core.NewPatchSubresourceAction(vaGroupResourceVersion, metav1.NamespaceNone, testPVName+"-"+testNodeName,
-					types.MergePatchType, patch(va(false /*attached*/, fin, ann),
+				core.NewPatchSubresourceAction(vaGroupResourceVersion, metav1.NamespaceNone,
+					testPVName+"-"+testNodeName,
+					types.MergePatchType, patch(va(false /*attached*/, fin /*finalizer*/, ann /* annotations */),
+						vaWithAttachError(va(false, fin, ann), "context deadline exceeded")),
+					"status"),
+				core.NewPatchAction(vaGroupResourceVersion, metav1.NamespaceNone, testPVName+"-"+testNodeName,
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:842]: Please add a comment that the finalizer is added again as a workaround / result of https://github.com/kubernetes-csi/external-attacher/issues/228

File: pkg/controller/csi_handler_test.go (hunk 8 above)
Comment (jsafrane) [reply pkg/controller/csi_handler_test.go:700]: This applies to all `ann` removed from `addedVA` below

File: pkg/controller/csi_handler_test.go [hunk 10]
```diff
@@ -1381,19 +1395,33 @@ func TestCSIHandler(t *testing.T) {
...
 				va(true /*attached*/, "" /*finalizer*/, nID /*annotations*/),
 				pvWithFinalizer(),
+				csiNode(),
 			},
 			listerResponse: map[string][]string{
 				// Intentionally empty
 			},
+			expectedActions: []core.Action{
+				// Finalizer is saved first
+				core.NewPatchAction(vaGroupResourceVersion, metav1.NamespaceNone, testPVName+"-"+testNodeName,
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:1418]: I think that saving of finalizers has been tested thoroughly in `TestCSIHandler` and here we don't need to test it again. So feel free to set it in `initialObjects`.

File: pkg/controller/csi_handler_test.go [hunk 11]
```diff
@@ -1381,19 +1395,33 @@ func TestCSIHandler(t *testing.T) {
...
+					types.MergePatchType, patch(va(false /*attached*/, "" /*finalizer*/, nil /* annotations */),
+						va(false /*attached*/, fin, nil))),
+				core.NewPatchSubresourceAction(vaGroupResourceVersion, metav1.NamespaceNone, testPVName+"-"+testNodeName,
+					types.MergePatchType, patch(va(false /*attached*/, "", nil),
+						va(false, "", nil)), "status"),
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:1423]: This change is odd:

* The patch is empty.  My tests show that the attacher indeed executes empty PATCH `{}`. Is there a bug in the attacher?

* While the resulting patch is empty, the way it's constructed is wrong - it expects that the volume gets detached (`va(false, ...`) - should it be `true`? The volume was attached successfully.

File: pkg/controller/csi_handler_test.go [hunk 12]
```diff
@@ -1414,11 +1442,12 @@ func TestCSIHandlerReconcileVA(t *testing.T) {
 		{
 			name: "va not attached actual state attached",
 			initialObjects: []runtime.Object{
-				va(false /*attached*/, "" /*finalizer*/, nID /*annotations*/),
+				deleted(va(false /*attached*/, "" /*finalizer*/, nID /*annotations*/)),
+				// va(false /*attached*/, "" /*finalizer*/, nID /*annotations*/),
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:1446]: good catch, please remove the commented line

File: pkg/controller/csi_handler_test.go (hunk 7 above)
Comment (msau42) [reply pkg/controller/csi_handler_test.go:37]: I think adding a unit test using one of the supported translated types would be good.

File: pkg/controller/csi_handler.go (hunk 4 above)
Comment (yuga711) [reply pkg/controller/csi_handler.go]: Done

File: pkg/controller/csi_handler.go (hunk 5 above)
Comment (yuga711) [reply pkg/controller/csi_handler.go]: Done

File: pkg/controller/csi_handler_test.go (hunk 8 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: Yes, agreed. Added ann back.

File: pkg/controller/csi_handler_test.go (hunk 9 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go:843]: done

File: pkg/controller/csi_handler_test.go (hunk 10 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: done

File: pkg/controller/csi_handler_test.go (hunk 11 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: Haven't found if there is a bug executing empty patch.
Fixed the patch construction logic in the test.

File: pkg/controller/csi_handler_test.go (hunk 12 above)
Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: thanks. done.

File: pkg/controller/framework_test.go [hunk 13]
```diff
@@ -224,6 +224,11 @@ func runTests(t *testing.T, handlerFactory handlerFactory, tests []testCase) {
 					t.Errorf("Failed to reconcile Volume Attachment objects: %v", err)
 				}
 			}
+			if !firstIter && (ctrl.vaQueue.Len() > 0 || ctrl.pvQueue.Len() > 0) {
```
[the remark this answers is not in the document]
Comment (yuga711) [reply pkg/controller/framework_test.go]: You are right. Added the iteration logic while experimenting with the tests.

File: pkg/controller/csi_handler_test.go [hunk 14]
```diff
@@ -1381,31 +1396,56 @@ func TestCSIHandler(t *testing.T) {
...
+					types.MergePatchType, patch(va(true /*attached*/, "", nil),
+						va(true, "", nil)), "status"),
+			},
 			expectedCSICalls: []csiCall{
 				{"attach", testVolumeHandle, testNodeID, nil, nil, false, nil, false, nil, 0},
 			},
 		},
+		/* TBD
+		{
+			name:           "GCE PD va attached actual state not attached",
```
Comment (jsafrane) [inline pkg/controller/csi_handler_test.go:1428]: In general, the patch looks good, is this the only thing missing?

Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: Here, I wanted to add a test with one of the supported translator types. Now planning to do that separately. I have created a github issue and added a TODO here.

Comment (yuga711) [reply pkg/controller/csi_handler_test.go]: > In general, the patch looks good, is this the only thing missing?
I wanted to add a test with one of the supported translator types. Now planning to do that separately. I have created a github issue and added a TODO here.
