### PR TITLE
Use rfc 6902 with finalizers

### LINKED ISSUE #1217: pv is stuck Terminating due to race condition when csi-attacher removes finalizer and csi-provisioner tries to remove another finalizer
**What happened**:
pv is stuck Terminating due to race condition when csi-attacher removes finalizer and csi-provisioner tries to remove another finalizer 

 - symptom
 pv is stuck Terminating when pvc is deleted

 - process
csi-attacher would remove the finalizer(e.g. external-attacher/disk-csi-azure-com) when pv is detached, and later on csi-provisioner the would try to remove the `external-provisioner.volume.kubernetes.io/finalizer` finalizer when pvc is deleted and since pv object is in the cache of provisioner , the finalizer deletion always fail until maximum 6 retries exceeds, and finally leaves the pv in Terminating state forever (the underlying storage is deleted before finalizer remove fails).

```
csi-attacher-disk	E0510 10:18:09.499513       1 csi_handler.go:701] Failed to remove finalizer from PV "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": PersistentVolume "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"kubernetes.io/pv-protection"}

csi-attacher-disk	I0510 10:18:09.510077       1 csi_handler.go:706] Removed finalizer from PV "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0"

csi-provisioner-disk	I0510 10:18:09.466810       1 controller.go:1517] delete "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": volume deleted

csi-azuredisk-controller	I0510 10:18:09.466386       1 azure_managedDiskController.go:325] azureDisk - deleted a managed disk: /subscriptions/xxx/resourceGroups/icto-1019_npi-lcm-cn-lcm-npi-cluster-01-nodes/providers/Microsoft.Compute/disks/pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0

csi-provisioner-disk	I0510 10:18:09.489676       1 controller.go:1554] delete "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": failed to remove finalizer for persistentvolume: Operation cannot be fulfilled on persistentvolumes "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": the object has been modified; please apply your changes to the latest version and try again

csi-provisioner-disk	W0510 10:18:09.489714       1 controller.go:989] Retrying syncing volume "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0", failure 6

csi-provisioner-disk	E0510 10:18:09.489752       1 controller.go:1007] error syncing volume "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": Operation cannot be fulfilled on persistentvolumes "pvc-b1c64ae1-6310-4a6c-aa44-12c80c9981a0": the object has been modified; please apply your changes to the latest version and try again
```
- workaround
remove all finalizers from the pv and then delete pv manually
```
kubectl patch pv NAME -p '{"metadata":{"finalizers":null}}'
```

/kind bug
cc @jsafrane 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version: v4.0.0
- Kubernetes version (use `kubectl version`): 1.27
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alam0rt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This PR replaces the CSI handler's patchPV (which uses a merge patch) with a  JSON patch (RFC 6902).

The problem with the merge patch is that if the controller holds a stale copy of the resource (which is likely if two controllers are trying to mutate finalizers at the same time),  finalizers may be added back inadvertently.

The problem this is solving is benign, but should solve it nonetheless. 
 
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-csi/external-provisioner/issues/1217

**Special notes for your reviewer**:

**Code created using claude-4.6-opus** (but reviewed and PR written by a human :) )

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controller/util.go [hunk 1]
```diff
@@ -225,3 +225,70 @@ func createMergePatch(original, new any) ([]byte, error) {
...
 	return patch, nil
 }
+
+// addFinalizerPatch creates a JSON Patch (RFC 6902) that appends a single
+// finalizer to the metadata.finalizers array without replacing the whole list.
+// This avoids a race where a merge-patch based on a stale informer cache
+// inadvertently re-adds finalizers that other controllers have already removed,
+// which causes 422 errors when the object is being deleted.
+// See https://github.com/kubernetes-csi/external-provisioner/issues/1217.
+func addFinalizerPatch(existingFinalizers []string, finalizerName string) ([]byte, error) {
```
Comment (alam0rt) [inline pkg/controller/util.go:235]: could be a bit wordy

Comment (jsafrane) [reply pkg/controller/util.go:235]: I think it is useful as it is. Better a wordy comment than no comment at all.
